config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :products
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
end

app/models/product.rb
class Product < ActiveRecord::Base
    
    belongs_to :user
    
    has_many :product_categories
    has_many :categories, through: :product_categories
    
    validates :name, presence: true, length: { minimum: 3, maximum: 50}
    validates :description, presence: true, length: { minimum: 10, maximum: 300}
    validates :user_id, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index
        @products = Product.paginate(page: params[:page], :per_page => 5)
    end
    
    def new
        @product = Product.new
    end
    
    def edit
    end
    
    def create
        #render plain: params[:product].inspect
        @product = Product.new( product_params )
        @product.user = current_user
        if @product.save
            # validation failed
            flash[:success] = "Product was successfully created"
            redirect_to product_path(@product)
        else
            # show the new product created
            render 'new'
        end
    end
    
    def update
        if @product.update(product_params)
           flash[:success] = "Product was successfully updated"
           redirect_to product_path(@product)
        else
            render 'edit'
        end
    end
    
    def show
    end
    
    def destroy
        @product.destroy
        flash[:danger] = "Product was successfully deleted"
        redirect_to products_path
    end
    
    private
    
        def set_product
            @product = Product.find(params[:id])
        end
        
        def product_params
            params.require(:product).permit(:name, :description, category_ids: [])
        end
        
        def require_same_user
            if current_user != @product.user and !current_user.admin?
               flash[:danger] = "You can only edit or delete your own product"
               redirect_to root_path
            end
        end
end

app/views/products/_form.html.erb
<%= render 'shared/errors', obj: @product %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for @product, :html => {class: "form-horizontal", role: "form"} do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :name %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :name, class: "form-control", placeholder:  "Name of product", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of product" %>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-offset-2 col-sm-8">
                        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
        <% end %>
        <div class="col-xs-6 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to products listing", products_path %> ]
        </div>
    </div>
</div>

app/views/products/_product.html.erb
<% obj.each do |product| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="product-name">
                    <%= link_to product.name, product_path(product) %>
                </div>
                <div class="product-body">
                    <%= truncate(product.description, length: 100) %>
                    <div class="product-meta-details">
                    <small>Created by: <%= product.user.username if product.user %>
                           <%= time_ago_in_words(product.created_at) %> ago,
                           last updated : <%= time_ago_in_words(product.updated_at) %> ago</small>
                    </div>
                </div>
                <% if product.categories.any? %>
                    <p>
                        Categories: <%= render product.categories %>
                    </p>
                <% end %>
                <% if logged_in? && (current_user == product.user || current_user.admin?) %>
                    <div class="product-actions">
                        <%= link_to "Edit this product", edit_product_path(product), class: "btn btn-xs btn-primary" %>
                        <%= link_to "Delete this product", product_path(product), method: :delete, 
                            data: {confirm: "Are you sure you want to delete this product?"}, 
                            class: "btn btn-xs btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1 align="center">Edit existing product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1 align="center">Listing all Products</h1>
<div align="center">
    <%= will_paginate %>
</div>
<%= render 'product', obj: @products %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/products/new.html.erb
<h1 align="center">Create a product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h2 align="center">Name: <%= @product.name %></h2>
<div class="well col-xs-12 col-offset-2">
    <% if @product.user %>
        <ul class="listing">
            <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                    <li>Created by:</li>
                    <li><%= link_to gravatar_for(@product.user), user_path(@product.user) %></li>
                    <li class="product-title">
                        <%= link_to @product.user.username, user_path(@product.user) %>
                    </li>
                    <li><small>
                            <%= pluralize(@product.user.products.count, "product") if @product.user.products %>
                        </small>
                    </li>
                </div>
            </div>
        </ul>
    <% end %>
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@product.description) %>
    <% if @product.categories.any? %>
        <p>Categories: <%= render @product.categories %></p>
    <% end %>
    <div class="product-actions">
        <% if logged_in? && (current_user == @product.user || current_user.admin?) %>
            <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this product", product_path(@product), method: :delete, 
                data: {confirm: "Are you sure you want to delete this product?"}, 
                class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "View all products", products_path, class: "btn btn-xs btn-success" %>
    </div>
</div>